TheInventory/Models/Inventory.cs
using TheInventory.Services;

namespace TheInventory.Models
{
    public class Inventory
    {
        //MATERIALS
        public List<Material> Materials = new List<Material>();

        //PARTS
        public List<Part> Parts = new List<Part>();

        //VEHICLES
        public List<Vehicle> Vehicles = new List<Vehicle>();

        public Inventory()
        {
            //MATERIALS
            Materials = Database.GetAllMaterials();

            //PARTS
            Parts = Database.GetAllParts();

            //VEHICLES
            Vehicles = Database.GetAllVehicles();
        }

        public void UpdateCount(string name, int count)
        {
            //MATERIALS
            Database.UpdateMaterialCount(name, count);

            //PARTS
            Database.UpdatePartCount(name, count);

            //VEHICLES
            Database.UpdateVehicleCount(name, count);
        }

        //Function to Get Count
        public int GetMaterialCount(string name)
        {
            //MATERIAL
            foreach(var material in Materials)
            {
                if (material.Name == name)
                {
                    return material.Count;  
                } 
            }
            return -1; 
        }

        public int GetPartCount(string name)
        {
            //PARTS
            foreach (var part in Parts)
            {
                if (part.Name == name)
                {
                    return part.Count;
                }
            }
            return -1;
        }

        public int GetVehicleCount(string name)
        {
            //VEHICLES
            foreach (var vehicle in Vehicles)
            {
                if (vehicle.Name == name)
                {
                    return vehicle.Count;
                }
            }
            return -1;
        }
    }
}

TheInventory/Models/Ticket.cs
namespace TheInventory.Models
{
    public class Ticket
    {

        //Fields
        public int Id { get; set; }
        public string Title { get; set; } = string.Empty;
        public string Department { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
        public string Status { get; set; } = string.Empty;

        private int count;

        public int Count
        {
            get
            {
                return count;
            }
            set
            {
                if (value > 0)
                    count = value;
                else
                    count = 0;
            }
        }

        //Constructor
        public Ticket(int newCount)
        {
            count = newCount;
        }
    }
}

TheInventory/Pages/About.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TheInventory.Pages
{
    public class AboutModel : PageModel
    {
        //Database Version / Connection Test
        public string Message = "";
        public void OnGet()
        {
            //Database Version / Connection Test
            Message = Services.Database.GetVersion();
        }
    }
}

TheInventory/Pages/Assembly.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using TheInventory.Models;

namespace TheInventory.Pages
{
    public class AssemblyModel : PageModel
    {
        public List<PartRecipe> allParts = new List<PartRecipe>();
        public List<VehicleRecipe> allVehicles = new List<VehicleRecipe>();
        public string Message { get; set; } = string.Empty;
        public bool MessageSuccess { get; set; } = false;

        [RegularExpression(@"^[A-Z]+[a-zA-Z0-9""'\s-]*$")]
        [StringLength(60, MinimumLength = 3)]
        [Required]
        public string Verify { get; set; } = "";
        public void OnGet(string message = "", bool success = true)
        {
            allParts = new PartRecipeBook().Parts;
            allVehicles = new VehicleRecipeBook().Vehicles;

            Message = message;
            MessageSuccess = success;
        }

        public IActionResult OnPostCraft(string name, int count, List<string> ingredient, string verify)
        {
            var success = new VehicleRecipeBook().CraftVehicleRecipe(name, count + 1, ingredient, verify);

            if (success)
            {
                return Redirect($"./Assembly?success=true&message=    {name} has been assembled.");
            }
            else
            {
                return Redirect($"./Assembly?success=false&message=    Verification Code is invalid!   Please enter a valid passcode");
            }
        }

        public IActionResult OnPostUpdate(string name, int count)
        {
            new Inventory().UpdateCount(name, count);

            return RedirectToPage("./Assembly");
        }
    }
}

TheInventory/Pages/Chart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TheInventory.Pages
{
    public class ChartModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

TheInventory/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace TheInventory.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

TheInventory/Pages/Garage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TheInventory.Models;

namespace TheInventory.Pages
{
    public class GarageModel : PageModel
    {

        public List<Vehicle> allVehicles = new List<Vehicle>();

        public int VehicleTotal = 0;
        public void OnGet()
        {
            allVehicles = new Inventory().Vehicles;

            VehicleTotal = Services.Database.TotalSumVehicleCount();
        }
    }
}

TheInventory/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TheInventory.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }

        //Page redirect on button form submit
        public IActionResult OnPost()
        {
            return RedirectToPage("Inventory");
        }
    }
}

TheInventory/Pages/Inventory.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using TheInventory.Models;


namespace TheInventory.Pages
{
    public class InventoryModel : PageModel
    {
        public List<Material> allMaterials = new List<Material>();

        public List<Part> allParts = new List<Part>();

        public List<Vehicle> allVehicles = new List<Vehicle>();

        public int MaterialTotal = 0; 
        public int PartTotal = 0; 
        public int VehicleTotal = 0;

        public string MaterialData = "";
        public string PartData = "";
        public string VehicleData = "";

        public void OnGet()
        {
            allMaterials = new Inventory().Materials;
            allParts = new Inventory().Parts;
            allVehicles = new Inventory().Vehicles;

            MaterialTotal = Services.Database.TotalSumMaterialCount();
            PartTotal = Services.Database.TotalSumPartCount();
            VehicleTotal = Services.Database.TotalSumVehicleCount();
        }

        /*//On Post Update function to update the database.
        public IActionResult OnPostUpdate(string name, int count)
        {
            Console.WriteLine($"{name} should change to {count}");
            new Inventory().UpdateCount(name, count);

            //Redirect back to normal get
            return RedirectToPage("./Inventory");
        }*/
    }
}

TheInventory/Pages/Manufacturing.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using TheInventory.Models;


namespace TheInventory.Pages
{
    public class ManufacturingModel : PageModel
    {
        public List<Material> allMaterials = new List<Material>(); 
        public List<PartRecipe> allParts = new List<PartRecipe>();
        public string Message { get; set; } = string.Empty;
        public bool MessageSuccess { get; set; } = false;

        [RegularExpression(@"^[A-Z]+[a-zA-Z0-9""'\s-]*$")]
        [StringLength(60, MinimumLength = 3)]
        [Required]
        public string Verify { get; set; } = "";
        public void OnGet(string message = "", bool success = true)
        {
            allMaterials = new Inventory().Materials;
            allParts = new PartRecipeBook().Parts;

            Message = message;
            MessageSuccess = success;
        }

        public IActionResult OnPostCraft(string name, int count, List<string> ingredient, string verify)
        {
            var success = new PartRecipeBook().CraftPartRecipe(name, count + 1, ingredient, verify);

            if (success)
            {
                return Redirect($"./Manufacturing?success=true&message= {name} has been manufactured.");
            }
            else
            {
                return Redirect($"./Manufacturing?success=false&message=    Verification Code is invalid!   Please enter a valid passcode.");
            }   
        }
        public IActionResult OnPostUpdate(string name, int count)
        {
            new Inventory().UpdateCount(name, count);

            return RedirectToPage("./Manufacturing");
        }
    }
}

TheInventory/Pages/NewTicket.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TheInventory.Models;
using TheInventory.Services;

namespace TheInventory.Pages
{
    public class NewTicketModel : PageModel
    {
        private List<Ticket> allTickets = new List<Ticket>();

        public void OnGet()
        {
            allTickets = Database.GetAllTickets();
        }

        public IActionResult OnPostAdd(string title, string department, string description, string status)
        {
            Database.NewTicket(title, department, description, status);
            return RedirectToPage("./Ticket");
        }
    }
}

TheInventory/Pages/Ticket.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TheInventory.Models;

namespace TheInventory.Pages
{
    public class TicketModel : PageModel
    {
        public List<Ticket> allTickets = new List<Ticket>();
        public void OnGet()
        {
            //Call Database Get Function and display on website
            allTickets = new TicketBook().Tickets;
        }

        public IActionResult OnPostDelete(int id)
        {
            //Call Database Delete Function and reload the page
            Services.Database.DeleteTicket(id);
            return RedirectToAction("./Ticket");
        }
    }
}

TheInventory/Pages/Assembly.cshtml
@page
@model TheInventory.Pages.AssemblyModel
@{
    ViewData["Title"] = "Assembly";
}

<!--Assembly Container-->
<div class="container-fluid vh-100">

    @{
        if(Model.Message != "")
        {
            if(Model.MessageSuccess)
            {
                <div class="container-fluid alert alert-success alert-dismissible fade show text-center" role="alert">
                    <i class="fa fa-check px-2" aria-hidden="true"></i>
                    <strong>Success!    </strong>@Model.Message
                        <button type="button" class="btn" data-bs-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true"><i class="fa fa-times" aria-hidden="true"></i></span> 
                        </button>
                </div>
            }
            else
            {
                <div class="container-fluid alert alert-warning alert-dismissible fade show text-center" role="alert">
                    <i class="fa fa-exclamation-triangle px-2" aria-hidden="true"></i>
                    <strong>Warning!    </strong>@Model.Message
                        <button type="button" class="btn" data-bs-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true"><i class="fa fa-times" aria-hidden="true"></i></span> 
                        </button>
                </div>
            }
        }
    }

      <!--Top Navbar-->
    <nav class="navbar navbar-expand-lg sticky-top rounded-3 mb-3">
        <img class="opacity-25" src="images/car-manufacturing-white.png" alt="Vehicle assembly" width="32" style="margin:10px">
        <h4 class="opacity-50">@ViewData["Title"]</h4>
    </nav>

    <!--Vehicles Recipes-->
    <div class="row mt-1">    
        <!-- Craftable Recipes-->
        <div class="col-xl col-md-12 pb-3">
            <h3>Assemble New Vehicles</h3>
            <div class="card rounded-3 shadow-lg">
                <div class="card-header text-center sticky-top">
                    Vehicles
                </div>

                <div class="card-body scroll-card"> 
                    @foreach(var vehicle in Model.allVehicles)
                    {
                    <div class="card m-2 shadow-sm hover-effect @(vehicle.IsCraftable())">
                        <div class="row g-0">
                            
                            <div class="col-md-2 align-self-center">
                                <img class="p-3" src="/images/vehicle/car-white.png" alt="car" style="max-width: 100px">
                            </div>
                            <div class="col-md-2 align-self-center">
                                <div class="row align-content-center">
                                    <h5>@vehicle.Name</h5>
                                    <h5 style="float:right;">@vehicle.Count</h5>
                                    @*<p class="card-title">@vehicle.Vehicletype</p>*@
                                    <p class="card-title" style="color: #ffa01c">@vehicle.VehicleCategory</p>
                                </div>
                            </div>
                            <div class="col-md-2 align-self-center text-center">
                                <div class="row align-content-center">
                                    <h1 style="color: #69f0ae">@vehicle.Count</h1>
                                </div>
                            </div>

                            <div class="col-md-6 align-self-center float-end p-2">
                                @foreach(var ingredient in vehicle.Ingredients)
                                {
                                    if(ingredient != "")
                                    {
                                      
                                        <span class="badge mb-1">@ingredient</span>
                                    }
                                }
                                @{
                                    if(vehicle.IsCraftable())
                                    {
                                        <form method="post" asp-page-handler="craft" asp-route-name="@vehicle.Name" asp-route-count="@vehicle.Count">
                                            @{
                                                foreach(var ingredient in vehicle.Ingredients)
                                                {
                                                    <input type="hidden" name="ingredient[]" value="@ingredient"/>
                                                }
                                            }
                                            <div class="input-group">
                                                <input required type="password" class="form-control" name="verify" placeholder="Verification Code">
                                                <button class="btn btn-cta" type="submit" value="Craft Recipe">Craft</button>
                                            </div>
                                        </form>
                                    }
                                }
                            </div> 
                        </div>
                    </div>
                    }
                </div>   
            </div>
        </div>

        <!--Parts-->
        <div class="col-xl col-md-12 pb-3">
        <h3>Parts Instock</h3>
            <div class="card rounded-3 shadow-lg">
                <div class="card-header text-center sticky-top">
                    Parts
                </div>
                <div class="card-body scroll-card">
                    @foreach(var part in Model.allParts)
                    {
                    <div class="card mb-2 shadow-sm hover-effect">
                        <div class="row g-0">
                            <div class="col-md-4 align-self-center bg-light">
                                <img src="/images/part/motor-white.png" class="p-3" alt="part" style="max-width: 110px">
                            </div>
                            <div class="col-md-6">
                                <div class="card-body">
                                    <h5 class="card-title">@part.Name</h5>
                                    <p class="card-text" style="color: #ffa01c">@part.PartType</p>
                                </div>
                            </div>
                            <div class="col-md-2 align-self-center counter text-center">
                                <div class="col align-content-center">
                                    <h1 style="color: #69f0ae">@part.Count</h1>
                                </div>
                            </div>
                            @*<div class="col-md-6 align-self-center counter">
                                <div class="float-end p-2">
                                    <form method="post" asp-page-handler="update">
                                    <div class="input-group">
                                        <input class="form-controller count-box rounded-3" name="count" value="@part.Count" type="number" min="0" step="1"/>
                                        <input type="hidden" name="name" value="@part.Name" />
                                        <button class="btn btn-cta">Update</button>
                                    </div>
                                    </form>
                                </div>
                            </div>*@
                        </div>
                    </div>
                    }
                </div>
            </div>
        </div>
    <!--Parts-->
    </div>
    <!--Vehicle Recipes-->
</div>

TheInventory/Pages/Manufacturing.cshtml
 @page
@model TheInventory.Pages.ManufacturingModel
@{
    ViewData["Title"] = "Manufacturing";
}


<!--Manufacturing Container-->
<div class="container-fluid vh-100">

    @{
        if(Model.Message != "")
        {
            if(Model.MessageSuccess)
            {
                <div class="container-fluid alert alert-success alert-dismissible fade show text-center" role="alert">
                    <i class="fa fa-check px-2" aria-hidden="true"></i>
                    <strong>Success!    </strong>@Model.Message
                        <button type="button" class="btn" data-bs-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true"><i class="fa fa-times" aria-hidden="true"></i></span> 
                        </button>
                </div>
            }
            else
            {
                <div class="container-fluid alert alert-warning alert-dismissible fade show text-center" role="alert">
                    <i class="fa fa-exclamation-triangle px-2" aria-hidden="true"></i>
                    <strong>Warning! </strong>@Model.Message
                        <button type="button" class="btn" data-bs-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true"><i class="fa fa-times" aria-hidden="true"></i></span> 
                        </button>
                </div>
            }
        }
    }

    <!--Top Navbar-->
  <nav class="navbar navbar-expand-lg sticky-top rounded-3 mb-3">
      <img class="opacity-25" src="images/factory-machine-white.png" alt="Manufacturing" width="32" style="margin:10px">
    <h4 class="opacity-50">@ViewData["Title"]</h4>
  </nav>

    <!--Parts Recipes-->
    <div class="row mt-1">    
        <!-- Craftable Recipes-->
        <div class="col-xl col-md-12 pb-3">
            <h3>Manufacture Parts</h3>
            <div class="card rounded-3 shadow-lg">
                <div class="card-header text-center sticky-top">
                    Parts
                </div>

                <div class="card-body scroll-card">
                    @foreach(var part in Model.allParts)
                    {
                    <div class="card m-2 shadow-sm hover-effect @(part.IsCraftable())">
                        <div class="row g-0">

                            <div class="col-md-2 align-self-center">
                                <img class="p-3" src="/images/part/motor-white.png" alt="part" style="max-width: 100px">
                            </div>
                            <div class="col-md-2 align-self-center">
                                <div class="col align-content-center">
                                    <h5>@part.Name</h5>
                                    @*<h2 style="">@part.Count</h2>*@
                                    @*<p class="card-title">@part.Description</p>*@
                                    <p class="card-title" style="color: #ffa01c">@part.PartCategory</p>
                                </div>
                            </div>
                            <div class="col-md-2 align-self-center text-center">
                                <div class="col align-content-center">
                                    <h1 style="color: #69f0ae">@part.Count</h1>
                                </div>
                            </div>
                            <div class="col-md-6 align-self-center float-end p-2">
                                @foreach(var ingredient in part.Ingredients)
                                {
                                    if(ingredient != "")
                                    {
                                        <span class="badge mb-2">@ingredient</span>
                                    }
                                }
                                @{
                                    if(part.IsCraftable())
                                    {
                                        <form method="post" asp-page-handler="craft" asp-route-name="@part.Name" asp-route-count="@part.Count">
                                            @{
                                                foreach(var ingredient in part.Ingredients)
                                                {
                                                    <input type="hidden" name="ingredient[]" value="@ingredient"/>
                                                }
                                            }
                                            <div class="input-group">
                                                <input required type="password" class="form-control" name="verify" placeholder="Verification Code">
                                                <button class="btn btn-cta" type="submit" value="Craft Recipe">Craft</button>
                                            </div>
                                        </form>
                                    }
                                }
                            </div> 
                        </div>
                    </div>
                    }
                </div>   
            </div>
        </div>

        <!--Materials-->
        <div class="col-xl col-md-12 pb-3">
        <h3>Update Materials</h3>
            <div class="card rounded-3 shadow-lg">
                <div class="card-header text-center sticky-top">
                    Materials
                </div>
                <div class="card-body scroll-card">
                    @foreach(var material in Model.allMaterials)
                    {
                    <div class="card mb-2 shadow-sm hover-effect">
                        <div class="row g-0">
                            <div class="col-md-2 align-self-center">
                                <img src="@material.ImageUrl" class="p-3" alt="material" style="max-width: 100px">
                            </div>
                            <div class="col-md-2">
                                <div class="card-body">
                                    <h5 class="card-title">@material.Name</h5>
                                    <p class="card-text" style="color: #ffa01c">@material.MaterialType</p>
                                </div>
                            </div>
                            <div class="col-md-2 align-self-center counter text-center">
                                <div class="col align-content-center">
                                    <h1 style="color: #69f0ae">@material.Count</h1>
                                </div>
                            </div>

                            <div class="col-md-6 align-self-center counter">
                                <div class="float-end p-2">
                                    <form method="post" asp-page-handler="update">
                                    <div class="input-group">
                                        <input class="form-controller count-box rounded-3" name="count" value="@material.Count" type="number" min="0" step="1"/>
                                        <input type="hidden" name="name" value="@material.Name" />
                                        <button class="btn btn-cta">Update</button>
                                    </div>
                                    </form>
                                </div>
                            </div>   
                        </div>
                    </div>
                    }
                </div>
            </div>
        </div>
    <!--Materials-->
    </div>
    <!--Parts Recipes-->
</div><!--Manufacturing Container-->

TheInventory/Pages/NewTicket.cshtml
@page
@model TheInventory.Pages.NewTicketModel
@{
    ViewData["Title"] = "New Ticket Form";
}

<!--Top Navbar-->
  <nav class="navbar navbar-expand-lg bg-light sticky-top rounded-3">
      <img class="opacity-25" src="images/ticket.png" alt="New Ticket" width="32" style="margin:10px">
    <h4 class="opacity-50">@ViewData["Title"]</h4>
  </nav>

  <div class="container">
    <div class="row m-3">
        <h2>Add a new Ticket</h2>
        
         <form method="post" asp-page-handler="add">
            <label for="title">Title</label>
            <input class="form-control rounded-1" id="title" type="text" name="title" placeholder="Ticket title..">

            <label for="department">Department</label>
            <select class="form-control rounded-1" id="department" type="text" name="Department">
                <option value="warehouse">Warehouse</option>
                <option value="manufacturing">Manufacturing</option>
                <option value="assembly">Assembly</option>
                <option value="sales">Sales</option>     
            </select>

            <label for="description">Description</label>
            <textarea class="form-control rounded-1" id="description" name="description" placeholder="Ticket description.." style="height:100px"></textarea>

            <label for="status">Status</label>
            <select class="form-control rounded-1" id="status" type="text"  name="Status">
                <option value="open">Open</option>
                <option value="pending">Pending</option>
                <option value="closed">Closed</option>
            </select>

            <button class="btn btn-cta" type="submit" value="Add">Add</button>
         
        </form>
    </div>
</div>

TheInventory/Pages/Ticket.cshtml
@page
@model TheInventory.Pages.TicketModel
@{
    ViewData["Title"] = "Ticket";
}



<div class="container-fluid" style="height: 100vh">
    <!--Top Navbar-->
  <nav class="navbar navbar-expand-lg bg-light sticky-top rounded-3">
      <img class="opacity-25" src="images/ticket-white.png" alt="Tickets" width="32" style="margin:10px">
    <h4 class="opacity-50">@ViewData["Title"]</h4>
  </nav>
        <div class="row mt-3">
            <div>
                <a class="btn btn-cta" asp-page="./NewTicket">New Ticket</a>
            </div>
             @foreach(var ticket in Model.allTickets)
            {
              <div class="col-sm-6 mt-2">
                <div class="card ">
                    <h6 class="card-header text-secondary">Ticket
                        <span class="badge rounded-pill bg-warning float-end">@ticket.Status</span>
                    </h6>
                  <div class="card-body">
                    <h5 class="card-title">@ticket.Title</h5>
                    <h6 class="card-title text-secondary">@ticket.Department</h6>
                    <p class="card-text text-truncate">@ticket.Description</p>

                        <!--Delete Form Button-->
                        <form class="float-end mx-1" method="post" asp-page-handler="delete" asp-route-id="ticket.id">
                            <input class="btn-cta"type="hidden" name="id" value="@ticket.Id" />
                            <button class="btn btn-cta btn-sm" type="submit" value="Delete" placeholder="Delete">Delete</button>
                        </form> 
                        @*<button class="float-end btn btn-cta btn-sm mx-1" type="submit" value="View">View</button>
                        <button class="float-end btn btn-cta btn-sm mx-1" type="submit" value="Edit">Edit</button>*@
                  </div>
                </div>
              </div>
              }
        </div>
        
</div>

  